import type { AdminExercise } from './db'

type SeedExercise = Omit<AdminExercise, 'createdAt' | 'updatedAt'>

export const DEFAULT_EXERCISES: SeedExercise[] = [
  {
    id: 'push_up',
    name: 'Push-Up',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE', 'GENERAL_FITNESS', 'LOSE_FAT'],
    sets: '3–4 sets', reps: '10–20 reps', tempo: '2-1-1-0', rest: '45–60 sec',
    howTo: [
      'Place hands shoulder-width apart, fingers pointing forward.',
      'Keep body in a straight line from head to heels — brace your core.',
      'Lower chest to 2–3 cm from the floor by bending elbows at 45°.',
      'Press back to the start. Exhale on the way up.',
    ],
    commonErrors: [
      'Sagging hips — core is not braced.',
      'Flaring elbows out to 90° — strains shoulder joint.',
      'Partial range of motion — reduces chest activation.',
    ],
    benefits: ['Builds chest, shoulders, and triceps simultaneously', 'Strengthens the core isometrically', 'Improves upper-body pushing strength with zero equipment'],
    bodyEffect: 'Activates pectoralis major (stretch-shortening cycle), long head of triceps, and anterior deltoid. The eccentric phase causes micro-tears repaired during rest → hypertrophy.',
    caloriesBurned: '~7–10 kcal/min',
    muscleEmoji: '💪',
    estimatedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE', 'LOSE_FAT', 'GENERAL_FITNESS'],
    sets: '3–4 sets', reps: '12–20 reps', tempo: '3-1-2-0', rest: '60 sec',
    howTo: [
      'Stand feet shoulder-width, toes 15–30° out.',
      'Brace core, keep chest tall. Begin by pushing hips back.',
      'Lower until thighs are parallel to the floor (or deeper if mobility allows).',
      'Drive through heels to stand. Squeeze glutes at top.',
    ],
    commonErrors: ['Knees caving inward (valgus collapse).', 'Heels lifting — limited ankle mobility.', 'Rounding the lower back at the bottom.'],
    benefits: ['Builds quad and glute mass', 'Improves hip mobility and knee stability', 'Largest lower-body compound movement — high calorie burn'],
    bodyEffect: 'Stimulates quads (rectus femoris, vastus group), gluteus maximus, and adductors. Depth determines glute vs quad emphasis. Causes significant metabolic demand due to large muscle mass involved.',
    caloriesBurned: '~8–12 kcal/min',
    muscleEmoji: '🦵',
    estimatedMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1544067032-81da16caebd2?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'deadlift_bb',
    name: 'Barbell Deadlift',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['BACK', 'HAMSTRINGS', 'GLUTES'],
    secondaryMuscles: ['CORE', 'FOREARMS', 'QUADS'],
    equipment: 'BARBELL',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['BUILD_MUSCLE', 'GENERAL_FITNESS'],
    sets: '3–5 sets', reps: '3–8 reps', tempo: '2-0-1-1', rest: '2–3 min',
    howTo: [
      'Bar over mid-foot, feet hip-width. Grip just outside legs.',
      'Hinge at hips, neutral spine. Bar close to shins.',
      'Brace hard — 360° core tension. Drive floor away.',
      'Lock out by squeezing glutes. Lower with control, hinge first.',
    ],
    commonErrors: ['Rounding the lower back (most dangerous)', 'Bar drifting forward — increases lever arm', 'Jerking the bar — momentum replaces strength'],
    benefits: ['Develops posterior chain (back, glutes, hamstrings) comprehensively', 'Increases grip strength', 'Greatest hormonal stimulus of any exercise (testosterone, GH)'],
    bodyEffect: 'Recruits erector spinae, glutes, hamstrings, and lats. The isometric back hold develops spinal erectors. High CNS demand → leads to strength adaptation via neural recruitment.',
    caloriesBurned: '~10–14 kcal/min',
    muscleEmoji: '🔙',
    estimatedMinutes: 40,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'bench_press_db',
    name: 'Dumbbell Bench Press',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['CHEST'],
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'DUMBBELL',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['BUILD_MUSCLE'],
    sets: '3–4 sets', reps: '8–12 reps', tempo: '3-1-2-0', rest: '90 sec',
    howTo: [
      'Lie on bench. Dumbbells at chest level, palms forward.',
      'Arch back slightly, feet flat. Retract scapula.',
      'Press up and slightly in — dumbbells touch at the top.',
      'Lower slowly until elbows are 45° below shoulder height.',
    ],
    commonErrors: ['Bouncing off chest', 'Wrists bending back under load', 'Not retracting scapula — reduces chest tension'],
    benefits: ['Greater range of motion than barbell', 'Corrects strength imbalances between sides', 'Safer for shoulder joints'],
    bodyEffect: 'Sternal head of pec major under maximum stretch at bottom — crucial for hypertrophy. DBs allow more natural arc of motion reducing impingement risk.',
    caloriesBurned: '~6–8 kcal/min',
    muscleEmoji: '💪',
    estimatedMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'pull_up',
    name: 'Pull-Up',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['BACK', 'BICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: 'PULL_UP_BAR',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['BUILD_MUSCLE', 'GENERAL_FITNESS'],
    sets: '3–4 sets', reps: '5–12 reps', tempo: '2-1-3-0', rest: '90 sec',
    howTo: [
      'Hang with overhand grip slightly wider than shoulders.',
      'Depress and retract scapula before pulling.',
      'Drive elbows toward hips, chin over bar.',
      'Lower slowly — 3 seconds. Full extension at bottom.',
    ],
    commonErrors: ['Kipping / using momentum', 'Not reaching full extension — reduces lat stretch', 'Shrugging shoulders up'],
    benefits: ['Best bodyweight back exercise', 'Develops lat width for V-taper', 'Strengthens biceps and grip simultaneously'],
    bodyEffect: 'Latissimus dorsi undergoes full stretch-to-peak-contraction ROM. The slow eccentric heavily targets long head of biceps. Improved shoulder stability.',
    caloriesBurned: '~8–10 kcal/min',
    muscleEmoji: '🔙',
    estimatedMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'shoulder_press_db',
    name: 'Dumbbell Shoulder Press',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['SHOULDERS'],
    secondaryMuscles: ['TRICEPS', 'CORE'],
    equipment: 'DUMBBELL',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE', 'GENERAL_FITNESS'],
    sets: '3–4 sets', reps: '10–15 reps', tempo: '2-1-2-0', rest: '60–90 sec',
    howTo: [
      'Sit upright, back supported. Dumbbells at ear level, elbows 90°.',
      'Press directly overhead — don\'t flare forward.',
      'Bring dumbbells close at top without locking elbows hard.',
      'Lower slowly back to start.',
    ],
    commonErrors: ['Leaning back (lumbar hyperextension)', 'Pressing in front of head rather than straight up', 'Flaring elbows forward at start'],
    benefits: ['Develops all three deltoid heads', 'Increases overhead stability', 'Improves posture'],
    bodyEffect: 'Anterior and medial deltoids are primary movers. Supraspinatus stabilises shoulder joint. Triceps provide elbow extension power.',
    caloriesBurned: '~5–7 kcal/min',
    muscleEmoji: '🏋️',
    estimatedMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'plank',
    name: 'Plank',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['CORE'],
    secondaryMuscles: ['SHOULDERS', 'GLUTES'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE', 'LOSE_FAT', 'GENERAL_FITNESS'],
    sets: '3 sets', reps: '30–90 sec hold', tempo: 'Hold', rest: '45–60 sec',
    howTo: [
      'Forearms on floor, elbows under shoulders.',
      'Body perfectly straight — squeeze glutes and quads.',
      'Pull navel slightly toward spine — brace transverse abdominis.',
      'Breathe normally. Do not hold breath.',
    ],
    commonErrors: ['Hips sagging down', 'Hips piking too high', 'Head dropping / looking forward'],
    benefits: ['Strengthens the anti-extension core', 'Transfers to every sport and lift', 'Reduces lower-back pain risk'],
    bodyEffect: 'Transverse abdominis (deep core) acts isometrically to resist spinal extension. Rectus abdominis and obliques co-contract. This builds core stiffness — the foundation of all compound lifts.',
    caloriesBurned: '~3–5 kcal/min',
    muscleEmoji: '🎯',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CALVES', 'CORE'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE', 'LOSE_FAT', 'GENERAL_FITNESS'],
    sets: '3 sets', reps: '12 reps per leg', tempo: '2-1-2-0', rest: '60 sec',
    howTo: [
      'Stand upright. Step forward with one foot.',
      'Lower rear knee toward floor — stop 2 cm before touching.',
      'Front knee tracks over second toe. Push off heel to next step.',
      'Alternate legs for prescribed reps.',
    ],
    commonErrors: ['Front knee caving inward', 'Torso leaning too far forward', 'Short stride — puts excessive knee stress'],
    benefits: ['Unilateral — corrects leg strength imbalances', 'Improves hip flexor mobility', 'High glute activation'],
    bodyEffect: 'Step length determines glute vs quad bias. Longer stride = more glute activation. Shorter stride = more quad dominant. Also develops single-leg stability through hip abductors.',
    caloriesBurned: '~6–9 kcal/min',
    muscleEmoji: '🦵',
    estimatedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'bicep_curl_db',
    name: 'Dumbbell Bicep Curl',
    sanskritName: '',
    category: 'STRENGTH',
    primaryMuscles: ['BICEPS'],
    secondaryMuscles: ['FOREARMS'],
    equipment: 'DUMBBELL',
    difficulty: 'BEGINNER',
    suitableFor: ['BUILD_MUSCLE'],
    sets: '3–4 sets', reps: '10–15 reps', tempo: '2-1-3-0', rest: '60 sec',
    howTo: [
      'Stand, arms hanging, palms forward.',
      'Curl dumbbell toward shoulder — keep elbow pinned to side.',
      'Squeeze bicep hard at peak.',
      'Lower slowly in 3 seconds — feel the stretch.',
    ],
    commonErrors: ['Swinging the torso (cheating)', 'Elbows drifting forward', 'Short range of motion — not extending fully'],
    benefits: ['Direct bicep hypertrophy', 'Improves grip strength and endurance', 'Better arm aesthetics'],
    bodyEffect: 'Biceps brachii (long and short head) contract concentrically. Slow eccentric produces the most muscle damage per rep. Brachialis and brachioradialis synergise.',
    caloriesBurned: '~4–6 kcal/min',
    muscleEmoji: '💪',
    estimatedMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'surya_namaskar',
    name: 'Surya Namaskar',
    sanskritName: 'Sun Salutation',
    category: 'YOGA',
    primaryMuscles: ['FULL_BODY'],
    secondaryMuscles: [],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['GENERAL_FITNESS', 'IMPROVE_FLEXIBILITY', 'LOSE_FAT'],
    sets: '5–12 rounds', reps: '1 round = 12 poses', tempo: 'Breath-linked', rest: 'None between rounds',
    howTo: [
      'Pranamasana: Stand in Tadasana, palms together at chest.',
      'Hastauttanasana: Inhale, raise arms overhead, slight backbend.',
      'Uttanasana: Exhale, fold forward — hands to floor.',
      'Ashwa Sanchalanasana: Inhale, right leg back, knee down, look up.',
      'Parvatasana: Exhale, both legs back — Downward Dog.',
      'Ashtanga Namaskar: Lower to 8-point (knees, chest, chin, hands, feet).',
      'Bhujangasana: Inhale, press chest up — Cobra.',
      'Repeat Parvatasana, Ashwa Sanchalanasana, Uttanasana, Hastauttanasana.',
      'Pranamasana: Exhale, palms together. Repeat other side.',
    ],
    commonErrors: ['Holding breath between poses', 'Sinking lower back in cobra', 'Hips too high in Ashwa Sanchalanasana'],
    benefits: ['Warms up every joint in 12 minutes', 'Improves cardiovascular endurance', 'Reduces morning stiffness and cortisol'],
    bodyEffect: 'Rhythmic breath-movement synchronisation activates parasympathetic nervous system. Spinal flexion-extension lubricates discs. 1 round at moderate pace burns ~4–5 kcal.',
    caloriesBurned: '~4–8 kcal/min',
    muscleEmoji: '🧘',
    estimatedMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'warrior_2',
    name: 'Warrior II',
    sanskritName: 'Virabhadrasana II',
    category: 'YOGA',
    primaryMuscles: ['QUADS', 'HIP_FLEXORS'],
    secondaryMuscles: ['GLUTES', 'SHOULDERS'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: 'Hold each side', reps: '30–60 sec per side', tempo: 'Static hold', rest: 'Transition to next pose',
    howTo: [
      'Step feet 4 feet apart. Turn right foot out 90°, left foot in 15°.',
      'Bend right knee over second toe — thigh parallel to floor.',
      'Extend arms parallel to floor. Gaze over front fingertips.',
      'Square hips to side. Breathe into the posture.',
    ],
    commonErrors: ['Front knee collapsing inward', 'Torso leaning forward', 'Raised shoulders — create tension not strength'],
    benefits: ['Opens hips and groins', 'Strengthens legs isometrically', 'Improves hip flexor mobility'],
    bodyEffect: 'Sustained isometric contraction of quadriceps and hip abductors. Lengthens hip flexor of the back leg. Improves hip ROM — directly translates to better squat depth.',
    caloriesBurned: '~3–5 kcal/min',
    muscleEmoji: '🧘',
    estimatedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'downward_dog',
    name: 'Downward-Facing Dog',
    sanskritName: 'Adho Mukha Svanasana',
    category: 'YOGA',
    primaryMuscles: ['HAMSTRINGS', 'CALVES', 'SPINE'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: '3–5 holds', reps: '30–60 sec hold', tempo: 'Static', rest: 'Child\'s pose between',
    howTo: [
      'Start on hands and knees — wrists under shoulders.',
      'Tuck toes, lift knees. Press hips up and back.',
      'Straighten legs as much as flexibility allows. Heels toward floor.',
      'Press hands firmly — spread fingers. Lengthen spine.',
    ],
    commonErrors: ['Rounding upper back', 'Locking knees hard — bends spine', 'Weight dumped into wrists — distribute through fingers'],
    benefits: ['Lengthens hamstrings and calves', 'Decompresses the spine', 'Strengthens shoulders and arms'],
    bodyEffect: 'Gravity creates traction along the spine decompressing lumbar discs. Hamstring group is placed in sustained eccentric stretch — improves passive flexibility over time.',
    caloriesBurned: '~3–4 kcal/min',
    muscleEmoji: '🧘',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'cobra',
    name: 'Cobra Pose',
    sanskritName: 'Bhujangasana',
    category: 'YOGA',
    primaryMuscles: ['SPINE', 'CHEST'],
    secondaryMuscles: ['SHOULDERS', 'GLUTES'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: '3–5 holds', reps: '20–30 sec hold', tempo: 'Breath-linked', rest: 'Balasana between',
    howTo: [
      'Lie face down. Palms under shoulders, elbows tucked.',
      'Inhale and press chest up. Keep lower ribs on mat (low cobra).',
      'Roll shoulders back and down. Gaze forward or slightly up.',
      'Exhale and lower slowly.',
    ],
    commonErrors: ['Pushing up too high — compresses lumbar', 'Straight arms (up-dog vs cobra distinction)', 'Shoulders raised to ears'],
    benefits: ['Counteracts desk-posture (thoracic kyphosis)', 'Strengthens spinal extensors', 'Opens chest and lungs'],
    bodyEffect: 'Erector spinae and multifidus (deep spinal stabilisers) contract to maintain the backbend. Pectorals and anterior shoulder fascia are placed in a gentle stretch — excellent for sedentary individuals.',
    caloriesBurned: '~2–3 kcal/min',
    muscleEmoji: '🧘',
    estimatedMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'tree_pose',
    name: 'Tree Pose',
    sanskritName: 'Vrikshasana',
    category: 'YOGA',
    primaryMuscles: ['GLUTES', 'CORE'],
    secondaryMuscles: ['CALVES', 'HIP_FLEXORS'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: 'Hold each side', reps: '30–60 sec per side', tempo: 'Static balance', rest: 'Between sides',
    howTo: [
      'Stand tall. Shift weight to right foot.',
      'Place left sole on right inner thigh (or calf — never knee).',
      'Hands at heart or overhead. Fix gaze on a point.',
      'Hold. Breathe calmly. Switch sides.',
    ],
    commonErrors: ['Foot pressing on the knee (unsafe)', 'Raised hip on standing leg', 'Holding breath affects balance'],
    benefits: ['Develops single-leg balance', 'Strengthens hip abductors', 'Improves proprioception and ankle stability'],
    bodyEffect: 'Challenges vestibular system and proprioception. Hip abductors work isometrically to prevent Trendelenburg sign. Improves neuromuscular control — directly reduces injury risk in sports.',
    caloriesBurned: '~2–3 kcal/min',
    muscleEmoji: '🧘',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1510894347713-fc3dc6166086?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    sanskritName: '',
    category: 'CARDIO',
    primaryMuscles: ['FULL_BODY'],
    secondaryMuscles: [],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['LOSE_FAT', 'IMPROVE_CARDIO', 'GENERAL_FITNESS'],
    sets: '3–4 sets', reps: '30–60 sec', tempo: 'Moderate pace', rest: '30 sec',
    howTo: [
      'Stand straight, arms at sides.',
      'Jump and simultaneously spread feet and raise arms overhead.',
      'Jump back to start. Land softly on balls of feet.',
      'Keep a consistent rhythmic pace.',
    ],
    commonErrors: ['Landing with stiff legs — shock through knees', 'Partial arm range of motion', 'Breath-holding'],
    benefits: ['Elevates heart rate quickly', 'Low-skill full-body warmup or finisher', 'Coordinates bilateral limb movement'],
    bodyEffect: 'Rapidly elevates heart rate to 60–80% max HR. Calves and hip abductors are primary movers. Effective for increasing VO₂ max over time when done progressively.',
    caloriesBurned: '~8–12 kcal/min',
    muscleEmoji: '🏃',
    estimatedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'burpee',
    name: 'Burpee',
    sanskritName: '',
    category: 'CARDIO',
    primaryMuscles: ['FULL_BODY'],
    secondaryMuscles: [],
    equipment: 'BODYWEIGHT',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['LOSE_FAT', 'IMPROVE_CARDIO'],
    sets: '3–5 sets', reps: '8–15 reps or 30 sec', tempo: 'Fast', rest: '60 sec',
    howTo: [
      'Stand. Drop hands to floor, jump feet back to plank.',
      'Perform a push-up.',
      'Jump feet forward between hands. Explode upward.',
      'Jump with arms overhead. Land softly.',
    ],
    commonErrors: ['Skipping the push-up (reduces upper body work)', 'Slamming the ground on landing', 'Lower back sagging in plank phase'],
    benefits: ['Maximum calorie burn in minimum time', 'Combines strength + cardio in one movement', 'No equipment needed'],
    bodyEffect: 'EPOC (Excess Post-Exercise Oxygen Consumption) is highest with burpees — you continue burning calories for up to 48 hrs after. Heart rate reaches 80–95% max.',
    caloriesBurned: '~12–15 kcal/min',
    muscleEmoji: '⚡',
    estimatedMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climbers',
    sanskritName: '',
    category: 'CARDIO',
    primaryMuscles: ['CORE', 'HIP_FLEXORS'],
    secondaryMuscles: ['SHOULDERS', 'QUADS'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['LOSE_FAT', 'IMPROVE_CARDIO', 'BUILD_MUSCLE'],
    sets: '3 sets', reps: '30–45 sec', tempo: 'Fast-paced', rest: '30–45 sec',
    howTo: [
      'Start in high plank. Arms straight under shoulders.',
      'Drive right knee toward chest.',
      'Switch legs rapidly in a running motion.',
      'Keep hips level throughout — don\'t bounce up.',
    ],
    commonErrors: ['Hips rising with each drive', 'Wrists behind shoulders (not under)', 'Slowing too much — loses cardio benefit'],
    benefits: ['Combines core work and cardio', 'Hip flexor strengthening', 'Shoulder stability under load'],
    bodyEffect: 'Rectus abdominis and transverse abdominis work to stabilise as hips try to flex. Psoas (hip flexor) under repeated concentric contraction. Heart rate maintained at 70–85% max HR.',
    caloriesBurned: '~9–13 kcal/min',
    muscleEmoji: '🏃',
    estimatedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'high_knees',
    name: 'High Knees',
    sanskritName: '',
    category: 'CARDIO',
    primaryMuscles: ['HIP_FLEXORS', 'QUADS'],
    secondaryMuscles: ['CORE', 'CALVES'],
    equipment: 'BODYWEIGHT',
    difficulty: 'BEGINNER',
    suitableFor: ['LOSE_FAT', 'IMPROVE_CARDIO'],
    sets: '3–4 sets', reps: '30–60 sec', tempo: 'Fast', rest: '30 sec',
    howTo: [
      'Stand, core engaged. Begin running in place.',
      'Drive knees to hip height with each step.',
      'Pump arms — opposite arm to leg for coordination.',
      'Land on balls of feet to protect joints.',
    ],
    commonErrors: ['Knees not reaching hip height (reduces effectiveness)', 'Leaning back', 'Landing on heels — impact injury risk'],
    benefits: ['Elevates HR to aerobic/anaerobic threshold fast', 'Strengthens hip flexors', 'Improves running mechanics'],
    bodyEffect: 'Psoas and iliacus (hip flexors) under maximum concentric load. Gastrocnemius and soleus absorb landing forces. Sustained effort improves VO₂ max and lactate threshold.',
    caloriesBurned: '~10–14 kcal/min',
    muscleEmoji: '🏃',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'box_jump',
    name: 'Box Jump',
    sanskritName: '',
    category: 'HIIT',
    primaryMuscles: ['QUADS', 'GLUTES', 'CALVES'],
    secondaryMuscles: ['CORE', 'HAMSTRINGS'],
    equipment: 'BODYWEIGHT',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['LOSE_FAT', 'IMPROVE_CARDIO', 'BUILD_MUSCLE'],
    sets: '4–5 sets', reps: '5–8 reps', tempo: 'Explosive', rest: '60–90 sec',
    howTo: [
      'Stand 30 cm from box. Athletic stance.',
      'Swing arms, hinge hips — countermovement dip.',
      'Explode upward — land softly with knees bent in the middle of the box.',
      'Step down carefully. Reset. Repeat.',
    ],
    commonErrors: ['Landing with straight knees — knee injury risk', 'Starting too close to box', 'Not using arm swing — reduces jump height'],
    benefits: ['Maximum power output development', 'EPOC effect burns fat long after exercise', 'Improves reactive strength'],
    bodyEffect: 'Stretch-shortening cycle is maximally challenged. Fast-twitch (Type II) muscle fibres are recruited exclusively during the concentric phase. Stimulates neuromuscular adaptations that improve all athletic performance.',
    caloriesBurned: '~12–16 kcal/min',
    muscleEmoji: '⚡',
    estimatedMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'kb_swing',
    name: 'Kettlebell Swing',
    sanskritName: '',
    category: 'HIIT',
    primaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    secondaryMuscles: ['CORE', 'BACK', 'SHOULDERS'],
    equipment: 'KETTLEBELL',
    difficulty: 'INTERMEDIATE',
    suitableFor: ['LOSE_FAT', 'BUILD_MUSCLE', 'IMPROVE_CARDIO'],
    sets: '4–5 sets', reps: '15–25 reps', tempo: 'Explosive hip hinge', rest: '60–90 sec',
    howTo: [
      'Stand, KB between feet. Hinge at hips, grip handle.',
      'Hike KB back between legs — load the hamstrings.',
      'Drive hips forward explosively — KB floats to shoulder height.',
      'Let it fall back through legs. Absorb with hips, not knees.',
    ],
    commonErrors: ['Squatting instead of hinging — quad-dominant, not glute-dominant', 'Pulling with arms instead of driving with hips', 'Losing neutral spine at bottom'],
    benefits: ['Develops posterior chain explosively', 'High caloric expenditure', 'Improves hip power for sports'],
    bodyEffect: 'The hip hinge pattern trains glutes and hamstrings for power, not just strength. Metabolic demand is high (similar to sprinting). Core anti-flexion under load builds real-world strength.',
    caloriesBurned: '~13–17 kcal/min',
    muscleEmoji: '⚡',
    estimatedMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'hip_flexor_stretch',
    name: 'Low Lunge Hip Flexor Stretch',
    sanskritName: '',
    category: 'FLEXIBILITY',
    primaryMuscles: ['HIP_FLEXORS'],
    secondaryMuscles: ['QUADS', 'GLUTES'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: 'Each side', reps: '30–60 sec hold', tempo: 'Static', rest: 'Transition to other side',
    howTo: [
      'Kneel on left knee, right foot forward — 90° front knee.',
      'Shift hips forward until tension felt at front of left hip.',
      'Keep torso upright. Breathe into the stretch.',
      'Option: raise left arm for deeper hip flexor stretch.',
    ],
    commonErrors: ['Front knee drifting over toes', 'Arching lower back to compensate', 'Bouncing into the stretch'],
    benefits: ['Counteracts sitting-induced hip flexor tightness', 'Improves squat and lunge depth', 'Reduces anterior pelvic tilt'],
    bodyEffect: 'Iliopsoas (psoas major + iliacus) is placed in lengthened position. Chronic tightness causes anterior pelvic tilt and lower back pain. Regular stretching restores neutral pelvic alignment.',
    caloriesBurned: '~2 kcal/min',
    muscleEmoji: '🤸',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
  {
    id: 'hamstring_stretch',
    name: 'Seated Hamstring Stretch',
    sanskritName: '',
    category: 'FLEXIBILITY',
    primaryMuscles: ['HAMSTRINGS'],
    secondaryMuscles: ['SPINE'],
    equipment: 'MAT',
    difficulty: 'BEGINNER',
    suitableFor: ['IMPROVE_FLEXIBILITY', 'GENERAL_FITNESS'],
    sets: 'Each side', reps: '30–45 sec hold', tempo: 'Static', rest: 'Between sides',
    howTo: [
      'Sit with one leg extended, other bent inward.',
      'Hinge forward from hips — not by rounding spine.',
      'Reach toward foot. Feel stretch in back of thigh.',
      'Breathe out to deepen. No bouncing.',
    ],
    commonErrors: ['Rounding spine (stretches back, not hamstrings)', 'Reaching too hard and holding breath', 'Bent knee on stretching leg reduces effectiveness'],
    benefits: ['Improves posterior chain flexibility', 'Reduces risk of hamstring strains', 'Helps squat and deadlift mechanics'],
    bodyEffect: 'Biceps femoris, semitendinosus, semimembranosus (hamstring group) undergo lengthening under mild neurological inhibition (autogenic inhibition via Golgi tendon organs). Sustained pressure over 30 sec increases plastic deformation in muscle-tendon unit.',
    caloriesBurned: '~2 kcal/min',
    muscleEmoji: '🤸',
    estimatedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=500&fit=crop&q=80',
    isPublished: true,
  },
]
